[book]
title = "Практический курс Rust"
authors = ["Tweede golf (оригинал)", "Участники проекта RustTraining-Rus (перевод)"]
language = "ru"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/r007/RustTraining-Rus"
edit-url-template = "https://github.com/r007/RustTraining-Rus/edit/main/training-book/src/{path}"
default-theme = "light"
preferred-dark-theme = "ayu"

[output.html.playground]
editable = true
line-numbers = true
